### ISSUE TITLE
第二步< 2. 在芝麻信用创建App并交换公钥是说这个只能app端ios/安卓用么？ 像我们纯前端能调用这个查么？

### ISSUE THREAD

**Issue by wuxiaolan91** [bmqb/zmxy#1]
第二步< 2. 在芝麻信用创建App并交换公钥是说这个只能app端ios/安卓用么？
像我们纯前端能调用这个查么？

**Comment by AlloVince** [comment]
是指在 芝麻信用商家服务平台 https://b.zmxy.com.cn/index.htm 创建一个平台内App
